version: '3.8'
services:
  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=caching_sha2_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: simons-db
      MYSQL_DATABASE: example
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - backnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./db/password.txt:/run/secrets/db-password:ro
    networks:
      - backnet
    depends_on:
      - db

networks:
  backnet: {}
